[package]
name = "shute"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = "1.18.0"
naga = { version = "22.1.0", features = ["glsl-in", "wgsl-in", "spv-out"] }
vulkano = { version = "0.34.1", default-features = false }
